### PR TITLE
kubernetes/nodejs-apply: Add future kubernetes-apply plugin example

### PR DESCRIPTION
**Pull request by briancain**

### CODE REVIEW

**Comment by krantzinator** [comment]
I don't get working deployment URLs when running against a kubernetes server installed on an EKS cluster. Can you let me know what environment you get working URLs in? Or if I need to adjust some config here?

**Comment by briancain** [comment]
@krantzinator - Does your pod have any errors shown post-deploy? I had an error initially with this, but the issue was my K8s couldn't pull in the built container. Locally I have to run my own container registry so I had to switch the example config to `local = false`. Otherwise my env is a kind+k8s cluster with a local container registry setup from the [helper script](https://github.com/hashicorp/waypoint/tree/main/contrib/serverinstall/kind-k8s).

**Comment by krantzinator** [comment]
With a server built off of `main` I am getting the below:
```
» Deploying...
✓ Executing kubectl apply...
 │ deployment.apps/my-deployment created
panic: runtime error: index out of range [1] with length 1

goroutine 37 [running]:
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000e72000, 0xc000c47e60, 0xc00043b300, 0xc000c6f953, 0x47340e0, 0xc000dcc6e0, 0x469d53, 0x2924660, 0x181b20)
```

**Comment by krantzinator** [comment]
My main concern, given all of the above, is that this example as-is does not seem to be enough information for someone to get an example going with the new k8s apply plugin.

**Comment by briancain** [comment]
> _EDIT:_ You can ignore that first error; I actually _wasn't_ using a `main` server. I've got other pressing things to do so I'm cutting myself off from a troubleshooting rabbit hole on my local  I can pick back up on this later.
> 
> With a server built off of `main` I am getting the below:
> 
> ```
> » Deploying...
> ✓ Executing kubectl apply...
>  │ deployment.apps/my-deployment created
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 37 [running]:
> github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000e72000, 0xc000c47e60, 0xc00043b300, 0xc000c6f953, 0x47340e0, 0xc000dcc6e0, 0x469d53, 0x2924660, 0x181b20)
> ```

This is an error from my status report branch. It's a bug I'm working on at the moment 😄

> 
> `kubectl logs` have a few interesting things; I _did_ just have to renew my gpg for my docker login so I might have other weirdness going on locally
> `2021-05-16T19:02:10.472Z [INFO] waypoint.server.grpc: error creating default hostname: err="rpc error: code = PermissionDenied desc = unregistered account"`
> 
> Looks like, yeah, getting same error as you
> `"my-deployment-7c64b76598-ncb69" is waiting to start: trying and failing to pull image`
> 
> If I change `local = false` it just fails outright:
> 
> ```
> 2021-05-16T19:05:07.404Z [TRACE] waypoint.server.grpc: event received: runner_id=01F5V91QP4RZTME6FV8537A5C4 event="&{error:{code:13  message:"unable to stream Docker logs to terminal: denied: requested access to the resource is denied"}}"
> ```
> 
> So I guess I get to stand up my own local registry also

Yep, you need to create a local docker container registry if you're going to be running locally and need to modify the container image name to reflect this (i.e. the name would be `localhost:5000/example-nodejs`), but I think that's not related to this example specifically.

The other k8s examples assume a working k8s environment. If we wanted a local container registry example, it would probably be similar to [nodejs-local-registry](https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/nodejs-local-registry) which I'm happy to provide as a separate project folder. I'd associate this example to be more inline with the regular [nodejs](https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/nodejs) example, which also doesn't assume you are using a local container registry.

I should also mention if you're running K8S on Docker Desktop for mac or windows, it comes with a functional container registry that k8s uses, so this example should work in that situation and the local situation is for k8s clusters that aren't configured with a container registry.

**Comment by briancain** [comment]
Rae and I synced on slack, and both agree that we need a better story on helping people bring up these example environments, but since that in itself is a larger task, we'll do it in a separate PR and this one is good to go.

**Pull request merged**
