### PR TITLE
Add Lambda example to waypoint

### PR DESCRIPTION
**Pull request by im2nguyen**
This adds a lambda/ruby example

### CODE REVIEW

**Review by briancain — APPROVED** [review]
Thanks for adding this! 🎉

**Review by krantzinator — APPROVED** [review]

**Review by topfunky — APPROVED** [review]
👍🏻

**Comment by mitchellh** [comment]
Note this doesn't need the Terraform at all since our plugin will create the ECR repository by default if it doesn't exist.

**Comment by im2nguyen** [comment]
Thanks for calling that out @mitchellh, I removed the terraform files after running through everything using waypoint only 

Also updated the lambda tutorial to reflect this

**Review by topfunky — APPROVED** [review]
👍🏻

**Pull request merged**
